server:
  port: 2000
spring:
  application:
    name: api-gateway

  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: provider1
          uri: lb://idc-provider1
          predicates:
            - Path=/p/**
          filters:
            - StripPrefix=1